{{- if .Values.openWebui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform.fullname" . }}-open-webui
  labels:
    {{- include "ai-platform.componentLabels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
spec:
  type: {{ .Values.openWebui.service.type }}
  ports:
    - port: {{ .Values.openWebui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-platform.openWebui.selectorLabels" . | nindent 4 }}
{{- end }}
