apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
spec:
  replicas: 0
  selector:
    matchLabels:
      name: teamcity-agent
  template:
    metadata:
      labels:
        name: teamcity-agent
      annotations:
        karpenter.sh/do-not-disrupt: "true"
    spec:
      serviceAccountName: teamcity-agent
      nodeSelector:
        internal: "true"
        compute: "cpu"
        processor: "amd64"
        workload: "compute-optimized"
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent:2026.1.3
          env:
            - name: SERVER_URL
              value: "http://teamcity-server-proxy.cicd.svc.cluster.local"
            - name: DOCKER_IN_DOCKER
              value: "start"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: wait-for-docker
              mountPath: /services/wait-for-docker.sh
              subPath: wait-for-docker.sh
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
              # ephemeral-storage: "100Gi"
            limits:
              memory: 2Gi
              # ephemeral-storage: "300Gi"
      volumes:
        - name: wait-for-docker
          configMap:
            name: teamcity-agent-wait-for-docker
            defaultMode: 0555