apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
  name: eks-ai-ape1

users:
- name: cluster-admin

contexts:
- context:
  name: dev-frontend
- context:
  name: dev-storage
- context:
  name: exp-test
