apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: 169446447120.dkr.ecr.ap-east-1.amazonaws.com/docker-hub/library/alpine:latest
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        stdin: true
        tty: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
