apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-serve-llm
spec:
  serveConfigV2: |
    applications:
    - name: llm-qwen3.5-9b-awq-4bit
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      runtime_env:
        pip:
          - vllm==0.18.0
          - pandas>=2.2.2
          - scipy>=1.14.0
      args:
        llm_configs:
        - model_loading_config:
            model_id: qwen3.5-9b-awq-4bit
            model_source: cyankiwi/Qwen3.5-9B-AWQ-4bit
          engine_kwargs:
            trust_remote_code: true
            dtype: bfloat16
            enable_chunked_prefill: true
            max_model_len: 8192
            gpu_memory_utilization: 0.95
          deployment_config:
            autoscaling_config:
              min_replicas: 0
              max_replicas: 4
              target_ongoing_requests: 64
            max_ongoing_requests: 128      
  rayClusterConfig:
    rayVersion: "2.54.1"
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        num-gpus: "0"
      template:
        spec:
          nodeSelector:
            karpenter.sh/nodepool: cpu-general-purpose-amd64-ec2
          containers:
          - name: ray-head
            image: 169446447120.dkr.ecr.ap-east-1.amazonaws.com/docker-hub/rayproject/ray-llm:2.54.1-py311-cu128
            ports:
            - containerPort: 8000
              name: serve
              protocol: TCP
            - containerPort: 8081
              name: metrics
              protocol: TCP
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: "5Gi"
              requests:
                cpu: "2"
                memory: "4Gi"
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 0
      maxReplicas: 2
      numOfHosts: 1
      groupName: gpu-group
      rayStartParams:
        num-gpus: "1"
      template:
        metadata:
          annotations:
        spec:
          nodeSelector:
             karpenter.sh/nodepool: gpu-a10g-ec2
          tolerations:
            - key: "nvidia.com/gpu"
              value: "true"
              effect: "NoSchedule"            
            - key: "ray.io/node-type"
              value: "worker"
              effect: "NoSchedule"
          containers:
          - name: ray-worker
            image: 169446447120.dkr.ecr.ap-east-1.amazonaws.com/docker-hub/rayproject/ray-llm:2.54.1-py311-cu128
            resources:
              limits:
                cpu: "32"
                memory: "256Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "8"
                memory: "32Gi"
                nvidia.com/gpu: "1"