apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm-host.fullname" . }}-config
  labels:
    {{- include "vllm-host.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.vllm.config | nindent 4 }}
