
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: "gpu-enabled-nodepool"
spec:
  template:
    metadata:
      labels:
        internal: "true"
        compute: "gpu"
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - "g"
            - "p"
        - key: "karpenter.sh/capacity-type" 
          operator: In
          values: 
            - "spot"
            - "on-demand"
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
        # prevent Ray head from being scheduled on GPU nodes
        - key: ray.io/node-type
          value: "worker"
          effect: NoSchedule
      nodeClassRef:
        name: "gpu-enabled-nodeclass"
        group: karpenter.k8s.aws
        kind: EC2NodeClass
      expireAfter: 720h
  limits:
    cpu: "80"
    memory: "320Gi"
    nvidia.com/gpu: "10"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: "15m"

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: "gpu-enabled-nodeclass"
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - id: ami-06fdfb0e2da4c8fcd # bottlerocket-aws-k8s-1.36-nvidia-x86_64-v1.64.0-ad9d4847
  role: "karpenter-eks-node-group-83e133e6a39377feb0c17d6365"
  instanceStorePolicy: "RAID0"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-ai-use1
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-ai-use1
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: "30Gi"
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: "100Gi"
        volumeType: gp3
        deleteOnTermination: true
  tags:
    nvidia.com/gpu: "true"
    auto-delete: "false"
    auto-stop: "false"