{{- if and .Values.litellm.dataPlane.enabled .Values.litellm.dataPlane.autoscaling.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-platform.fullname" . }}-litellm-secrets
  labels:
    {{- include "ai-platform.componentLabels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
type: Opaque
{{- with .Values.litellm.secrets }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
